MODE = 'MODE'
------------
MODE_DIRECT = 'DIRECT'
TARGET = 'TARGET'
------------
ALL_ITEMS_MATCHING_MAP_CATEGORY = "*"
------------
MODE_WEIGHT_BY = 'WEIGHT_BY'
CRITERIA = 'CRITERIA'
STACK_LIMIT = 'STACK_LIMIT'
------------
COMPARATOR = "COMPARATOR"
LOWER = "LOWER"
HIGHER = "HIGHER"
------------
STAT = "STAT"
STAT_HEALTH_PERCENTAGE = "HEALTH %"
STAT_STACK_AMOUNT = "STACK AMOUNT"
STAT_PROFICIENCY = "PROFICIENCY"
STAT_WEAPON_SCORE = "WEAPON SCORE"
STAT_WEAPON_ABILITY = "WEAPON ABILITY"
STAT_SKILL = "SKILL" -- Use Ext.Enums.SkillId
------------

WEAPON_MAP = {
	[ALL_ITEMS_MATCHING_MAP_CATEGORY] = {
		[MODE] = MODE_WEIGHT_BY,
		[CRITERIA] = {
			[1] = { [STAT] = STAT_WEAPON_ABILITY, [COMPARATOR] = HIGHER },
			[2] = { [STAT] = STAT_WEAPON_SCORE, [COMPARATOR] = HIGHER },
		}
	}
}

EQUIPMENT_MAP = {
	[ALL_ITEMS_MATCHING_MAP_CATEGORY] = {
		[MODE] = MODE_WEIGHT_BY,
		[CRITERIA] = {
			[1] = { [STAT] = STAT_PROFICIENCY },
		}
	}
}

TAGS_MAP = {
	["HEALING_POTION"] = {
		[MODE] = MODE_WEIGHT_BY,
		[CRITERIA] = {
			[1] = { [STAT] = STAT_HEALTH_PERCENTAGE, [COMPARATOR] = LOWER, },
			[2] = { [STAT] = STAT_STACK_AMOUNT, [COMPARATOR] = LOWER }
		},
		[STACK_LIMIT] = 2
	},
	["LOCKPICKS"] = {
		[MODE] = MODE_WEIGHT_BY,
		[CRITERIA] = {
			[1] = { [STAT] = STAT_SKILL, [STAT_SKILL] = "SleightOfHand", [COMPARATOR] = HIGHER, },
			[2] = { [STAT] = STAT_STACK_AMOUNT, [COMPARATOR] = HIGHER }
		}
	}
}
